### ISSUE TITLE
Create initiative fails

### ISSUE THREAD

**Issue by ajturner** [esridc/hub-py#84]
the initiative, site, groups are created, but not completely wired up together. 

```python
myInitiative = myHub.initiatives.add(title='Python new initiative20191217')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
----> 1 myInitiative = myHub.initiatives.add(title='Python new initiative20191217')
      2 myInitiative

~/Projects/esri/hub-py/arcgishub/hub.py in add(self, title, description, site, data, thumbnail)
    445         _initiative = Initiative(self._hub, item)
    446         if site is None:
--> 447             site = _initiative.sites.add(title=title, subdomain=title)
    448         else:
    449             site = self._hub.sites.clone(site, title)

~/Projects/esri/hub-py/arcgishub/sites.py in add(self, title, subdomain, groups)
    380 
    381         #Register site and update its data
--> 382         _data = self._create_and_register_site(site, subdomain, _site_data, group_ids)
    383 
    384         _data = json.dumps(_data)

~/Projects/esri/hub-py/arcgishub/sites.py in _create_and_register_site(self, site, subdomain, site_data, group_ids)
    179             #register site as an app
    180             _app_dict = site.register(app_type='browser', redirect_uris=[site.url])
--> 181             client_key = _app_dict['client_id']
    182 
    183             #Check for length of domain

TypeError: 'NoneType' object is not subscriptable
```

**Comment by Rushgrimes** [comment]
Hi Guys,   this issue is still open ?  is it resolvable ? 
I have the same issue cloning between 2 organisations (basic)   I get 'None Type'   object is not subscriptable 


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
In  [164]:
Line 1:     site = hub_basic.initiatives.clone(i1, origin_hub=myHub)

File c:\python_clone_env\arcgispro-py3_additional\src\arcgishub\arcgishub\hub.py, in clone:
Line 558:   new_site = self._hub.sites.clone(site, pages=True, title=title)

File c:\python_clone_env\arcgispro-py3_additional\src\arcgishub\arcgishub\sites.py, in clone:
Line 652:   _data = self._create_and_register_site(new_item, subdomain, site.definition, content_group_id, collab_group_id)

File c:\python_clone_env\arcgispro-py3_additional\src\arcgishub\arcgishub\sites.py, in _create_and_register_site:
Line 340:   client_key = _app_dict['client_id']

TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------------------------------

It would be nice if there is a solution or workaround
